### ISSUE TITLE
Adding a responsive theme

### ISSUE THREAD

**Issue by YaronMiro** [shoov/shoov.io#11]
- [Them info + sample](https://wrapbootstrap.com/theme/velocity-designed-for-products-WB0N38R04)
- [Live  theme](http://wrapbootstrap.com/preview/WB0N38R04)
- [x] Clean them from unnecessary `js` and `css`.
- [x] Replace assets with available packages via `bower`.
  - [x] Check if can replace the theme jQuery1.11.2 version with a newer version jQuery2.1.4
  - [x] Check if can remove jQuery-migrate if not using old jQuery version.

**Comment by YaronMiro** [comment]
Hi @niryariv
- Do we have a logo for shoov or I need to pickup some font and use that fro now ?
- Are there any social links for shoov ?
- I'm going to assign the `info@gizra.com`  mail for the form registration ok ?
- The address and contact details are exactly as Gizra site right  ? 
  Thank's

**Comment by niryariv** [comment]
- No logo, feel free to make one up if you like (but don't spend too much time on it and check the brochure to make sure it matches)
- No social links
- Please use `info+shoov@gizra.com` (@bricel perhaps create a shoov@gizra.com address)?
- Yes
