### ISSUE TITLE
make the gif smaller and the contact form larger

### ISSUE THREAD

**Issue by niryariv** [shoov/shoov.io#15]
- [x] basically the gif we have now isn't great and distracts the user too much - make it about %60 of the current size. (@amitai is preparing a new gif)
- [x] the contact form, OTOH, is a key element that we need to make sure the user doesn't miss - please make it stand out more, either by making it larger or adding a border etc, whatever you think is good.

**Comment by amitaibu** [comment]
@niryariv do you have an idea of a site to do a visual regression gif on?

**Comment by niryariv** [comment]
Ideally, ask permission from one on of our clients. less ideally, set up a fake site with some bootstrap theme, last option (if we don't have time for the above) gizra.com

**Comment by amitaibu** [comment]
I was thinking something like cnn/ nasa/ whitehouse.

**Comment by niryariv** [comment]
maybe, but i'd try to make it non-obvious which site it is
