### ISSUE TITLE
change lead text

### ISSUE THREAD

**Issue by niryariv** [shoov/shoov.io#16]
please remove the border around the first sentence, and use the following text (note capitalization on the first sentence - don't capitalize each word):

**Shoov performs the same function as a team of human QA testers**

Simulating any number of device/OS/Browser combinations accessing your website 24/7 in multiple, programmable scenarios, Shoov visually detects issues as they rise and alerts your team.

**Comment by amitaibu** [comment]
@niryariv Maybe we should make the first sentence more about _helping_ the QA team, so it won't create antagonism from QA people

**Comment by niryariv** [comment]
@RachelBaram do you have an idea for a better text?

**Comment by RachelBaram** [comment]
Shoov expands your team's testing cover/reach/scope/capacity (need to choose the word used by developers).

Brainstorming idea:
"More tests, run more often, on more browsers and platforms, both in development and live sites."

**Comment by niryariv** [comment]
let's discuss on sunday, we can change the site then

**Comment by YaronMiro** [comment]
Duplicated issue #26
