### ISSUE TITLE
make blog part less prominent

### ISSUE THREAD

**Issue by niryariv** [shoov/shoov.io#19]
![screen shot 2015-10-13 at 1 42 36 pm](https://cloud.githubusercontent.com/assets/1771/10452845/68f92d3a-71b0-11e5-9b1f-5221e11827ff.png)

I think it's a bit of an overkill, we want it available to users but i'm not sure we want to push it as much. Maybe have it as one element "learn more etc" and then the links, instead of having a boc for each post link?

@amitaibu thoughts?

**Comment by amitaibu** [comment]
one element should be fine.

**Comment by YaronMiro** [comment]
Done.
