### ISSUE TITLE
Replace gif

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov.io#22]
How about this one -- http://gfycat.com/HandmadeMarriedGrassspider ?

**Comment by niryariv** [comment]
עדיין לא ברור אבל עדיף מהראשון

**Comment by YaronMiro** [comment]
@niryariv 

^^ Should I add the this gif to the live site ?

**Comment by niryariv** [comment]
yes please

**Comment by amitaibu** [comment]
How about this one -- http://gfycat.com/ImpassionedRingedAmazondolphin

**Comment by amitaibu** [comment]
actually I think the UN one is better for now, until we change with an improved version
