### ISSUE TITLE
Remove sticky header

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov.io#23]
IMO it's not needed, and just adds a bit of noise to the page

![shoov_io](https://cloud.githubusercontent.com/assets/125707/10563037/0f927074-7581-11e5-99b9-8fc3270b4498.jpg)

@YaronMiro , What do you think?

**Comment by YaronMiro** [comment]
@amitaibu 
I wasn't sure if I like it, so I thought to give it a few days and hear other people opinions on the site design. Your opinion helped me to decide that it's not needed.
I will transform it to a non-sticky header with a dark blue color.

**Comment by niryariv** [comment]
@YaronMiro wait a bit, we're thinking about maybe putting a link to the trial form there - please don't change yet

**Comment by YaronMiro** [comment]
@amitaibu 
OK, I will wait to hear from you.

**Comment by amitaibu** [comment]
Closed in favor of other issues
