### ISSUE TITLE
remove "home", "glossary" and "tutorial" links from header

### ISSUE THREAD

**Issue by niryariv** [shoov/shoov.io#24]

**Comment by YaronMiro** [comment]
@niryariv 
- Once the `glossary` link is removed from the header then we will no longer have any link for it on the homepage.  The only place that we will have a link for `glossary` on the site is inside the first tutorial lesson.

![selection_006](https://cloud.githubusercontent.com/assets/3907724/10563477/23c19292-7594-11e5-8029-974a0056a9c6.png)
- The header will only include the `shoov logo` and the login link yes ?

**Comment by niryariv** [comment]
yes, that's ok

**Comment by YaronMiro** [comment]
Resolved on #22
