### ISSUE TITLE
homepage fixes

### ISSUE THREAD

**Issue by niryariv** [shoov/shoov.io#25]
- [x] replace locations
- [x] add "OR" between "Get Started .." and " Contact gizra ..."
- [x] capitalize "content" => "Content"

![screen shot 2015-10-18 at 12 09 27 pm](https://cloud.githubusercontent.com/assets/1771/10563408/a23c02b8-7591-11e5-8c5b-3692bfe1dd0a.png)

**Comment by YaronMiro** [comment]
@niryariv 
I'm guessing you meant capitalize "Contact" instead of  "content" ?

**Comment by niryariv** [comment]
exactly, sorry

**Comment by YaronMiro** [comment]
Resolved on #22
