### ISSUE TITLE
Improve live monitoring view

### ISSUE THREAD

**Issue by bricel** [shoov/shoov.io#28]
![https___app_shoov_io__code_303ba2b8be4c1fa6b18d__repos](https://cloud.githubusercontent.com/assets/165644/10930929/afea32b2-82cb-11e5-8d51-c11c35b1ac81.png)

**Comment by amitaibu** [comment]
Wrong repo :) 

Should be filed under shoov/shoov

Also, that's beyond the scope of the redesign.
