### ISSUE TITLE
Add quick survey after user register.

### ISSUE THREAD

**Issue by bricel** [shoov/shoov.io#35]
![join_now](https://cloud.githubusercontent.com/assets/165644/11925004/a2cd4272-a7bf-11e5-85b7-b31091c2e647.png)

**Comment by YaronMiro** [comment]
@bricel 
I can take this one if It's still relevant ?
If so then lets discuss Because IMO some of the thing on the example image are relevant and some are not.

**Comment by amitaibu** [comment]
Not needed for now.
