### ISSUE TITLE
Cant registered - URL does not recognize 

### ISSUE THREAD

**Issue by kazabooboo** [shoov/shoov.io#37]
Whatever you type in the URL field - site displays "please enter a url" 
<img width="1280" alt="screen shot 2016-02-03 at 3 38 21 pm" src="https://cloud.githubusercontent.com/assets/16226208/12796469/e349097c-ca8c-11e5-8a2b-d84c94d3d0de.png">

**Comment by amitaibu** [comment]
indeed - you are missing the `http://` part :)
